version: '3.9'
services:
  odd_agent:
    build: .
    ports:
      - "8501:8501"
    volumes:
      - ./:/app
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - NEWS_API_KEY=${NEWS_API_KEY}
      - SEC_API_KEY=${SEC_API_KEY}
